project:
  type: website

website:
  title: Star Power Analysis
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO523-Fall25-101-201/final-project-juan-nadal-solo
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Analysis
        href: analysis.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
      - text: Writeup
        href: writeup.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true

execute:
  freeze: true
